### ISSUE TITLE
Enemies don't appear to take damage from the grenades

### ISSUE THREAD

**Issue by jaredgav** [joshuaemer/Gold-Team#66] opened 2018-04-02 01:57 UTC
MINOR BUG
Enemies seem not to  be taking damage from the grenades. Especially when they get stuck on the map in a couple of places.

Recreate, Throw a grenade at the enemies. 

Alpha Windows release, Windows 10,  zip download

**Comment by joshuaemer** [comment] 2018-04-02 13:06
Thank you for reporting however they do deal damage we decided to keep the damage low. For specific numbers the grenades deal 20 damage per hit.   I am going to close this issue as it is not a bug.

**Closed** 2018-04-02 13:06 UTC
